Greeting.create!(message: 'Hello, Otto!')
Greeting.create!(message: 'Kedu, Otto!')
Greeting.create!(message: 'Bawoni, Otto!')
Greeting.create!(message: 'Yaya, Otto!')
Greeting.create!(message: 'Bwanji, Otto!')
